### PR TITLE
Rework with JQ parser and improvements

### PR DESCRIPTION
**Pull request by nailyk-fr**
* Use jq as json parser for 'text' entries
   to solve the telegram 'reply' issue.
 * Solve https://github.com/eelcohn/Telegram-API/issues/8 .
 * Maybe a way for https://github.com/eelcohn/Telegram-API/issues/6 .

### CODE REVIEW

**Comment by eelcohn** [comment]
Thans for this update. I'm not sure if I'll merge this one since this fix requires a third party app. I'll get back to it later.

**Comment by nailyk-fr** [comment]
Yes, it is a problem. 
This one took me a lot of time because I tried almost all the json tcl libs proposed on the 'official' wiki. 
No one worked because some structs of the result crash them.

**Comment by nailyk-fr** [comment]
Start of the rework with jq parser. 
Let me know :)

**Comment by eelcohn** [comment]
The reason that I'm a bit reluctant to adopt this one is because I'm trying not to depend on 3rd party modules as much as possible.
Have you tried the json package in tcllib yet? It's on my to-do list to try it and it's described here https://core.tcl.tk/tcllib/doc/trunk/embedded/www/tcllib/files/modules/json/json.html and here http://wiki.tcl.tk/40053

**Comment by nailyk-fr** [comment]
PR updated. 
Really not easy to test the disabled commands for me. 
I will try to rework them anyway.

**Comment by eelcohn** [comment]
Commit af30b7a is added to the main branch

**Comment by eelcohn** [comment]
Commit 1ba1559 is added to the main branch

**Comment by eelcohn** [comment]
First part of commit 0a427101 is added to the main branch (jq-0.4.0 added to lib/libjson.tcl)

**Comment by eelcohn** [comment]
Okay, finally merged this into the development branch. Will test all your work in the next few days :-)

**Comment by eelcohn** [comment]
I chose to put the jq code into a seperate library file (libjson.tcl) so that in the future it will be easier to add support for other JSON processors as well.

This comes in handy on systems which do not have the jq tool installed.

**Pull request closed without merging**
